name: "ESLint"
on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm ci
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v21
        with:
          config_path: "./eslint.config.mjs"
          extra_args: "--max-warnings=0"