name: "Unit Tests"
on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm ci
      - name: Run unit tests
        run: npm test